# Generated by Django 4.0.4 on 2022-07-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('contrasena', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
